### ISSUE TITLE
Build errors on kernel 4.1.15

### ISSUE THREAD

**Issue by mauriciocirelli** [linux4wilc/driver#3]
Dear,

We have found compile errors on current master branch, commit 1a0619d1b7489641838471417dcd9453efdca628. The issue is that it is doing a wrong kernel version check on file wilc1000/wilc_wfi_cfgoperations.c. All 4.1.x kernels use the same API, but it is checking only if kernel version is <= 4.1.0, causing issues when using kernels like 4.1.15.

This API has only changed on kernels >= 4.2.x.

Attached you will find a patch to fix it as .txt, because Github does not allow attaching .patch files.

[fix-kernel-version-check-wilc1000.txt](https://github.com/linux4wilc/driver/files/1551217/fix-kernel-version-check-wilc1000.txt)

**Comment by AdhamAbozaeid** [comment]
Thanks @mauriciocirelli for the patch. I integrated it to the development branch
