### ISSUE TITLE
Failed to start firmware WILC3000

### ISSUE THREAD

**Issue by TrilokJTReddy** [linux4wilc/driver#35]
Hi @AdhamAbozaeid ,
I have interfaced WILC3000 with SAMA5D27 processor(SPI).  Kernel is able to detect WILC device and load the firmaware but unable to start the firmware. I attached log and .dts file please have a look.

# modprobe wilc-spi
WILC_SPI spi0.0: spiModalias: wilc1000, spiMax-Speed: 12000000
(unnamed net_device) (uninitialized): INFO [wilc_create_wiphy]Registering wifi device
(unnamed net_device) (uninitialized): INFO [wilc_wfi_cfg_alloc]Allocating wireless device
(unnamed net_device) (uninitialized): INFO [wilc_create_wiphy]Successful Registering
(unnamed net_device) (uninitialized): INFO [wilc_create_wiphy]Registering wifi device
(unnamed net_device) (uninitialized): INFO [wilc_wfi_cfg_alloc]Allocating wireless device
(unnamed net_device) (uninitialized): INFO [wilc_create_wiphy]Successful Registering
WILC_SPI spi0.0: WILC got 74 for gpio_reset
WILC_SPI spi0.0: WILC got 68 for gpio_chip_en
WILC_SPI spi0.0: WILC got 73 for gpio_irq
wifi_pm : 0
wifi_pm : 1
WILC_SPI spi0.0: WILC SPI probe success
# \WILC_SPI spi0.0 wlan0: INFO [wilc_mac_open]MAC OPEN[c794a000] wlan0
WILC POWER UP
WILC_SPI spi0.0 wlan0: INFO [wilc_init_host_int]Host[c794a000][c72be400]
WILC_SPI spi0.0 wlan0: INFO [wilc_init]Initializing host interface for client 1
WILC_SPI spi0.0 wlan0: INFO [wilc_init]INIT: CLIENT COUNT 0
WILC_SPI spi0.0 wlan0: INFO [wilc_mac_open]*** re-init ***
WILC_SPI spi0.0 wlan0: INFO [wlan_init_locks]Initializing Locks ...
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_init]Initializing WILC_Wlan
WILC_SPI spi0.0 wlan0: INFO [init_chip]Bootrom sts = c
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_initialize]WILC Initialization done
WILC_SPI spi0.0 wlan0: INFO [init_irq]IRQ request succeeded IRQ-NUM= 121 on GPIO: 73
WILC_SPI spi0.0 wlan0: INFO [wlan_initialize_threads]Initializing Threads ...
WILC_SPI spi0.0 wlan0: INFO [wlan_initialize_threads]Creating kthread for transmission
WILC_SPI spi0.0 wlan0: INFO [linux_wlan_txq_task]txq_task Taking a nap
WILC_SPI spi0.0 wlan0: INFO [wlan_initialize_threads]Creating kthread for Debugging
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_get_firmware]Detect chip WILC3000
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_get_firmware]loading firmware mchp/wilc3000_wifi_firmware.bin
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_get_firmware]WLAN firmware: mchp/wilc3000_wifi_firmware.bin
WILC_SPI spi0.0 wlan0: INFO [wilc_firmware_download]Downloading Firmware ...
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_firmware_download]Downloading firmware size = 136076
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_firmware_download]Offset = 119296
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_firmware_download]Offset = 136076
WILC_SPI spi0.0 wlan0: INFO [wilc_firmware_download]Download Succeeded
WILC_SPI spi0.0 wlan0: INFO [linux_wlan_start_firmware]Starting Firmware ...
WILC_SPI spi0.0 wlan0: INFO [linux_wlan_start_firmware]Waiting for FW to get ready ...
WILC_SPI spi0.0 wlan0: INFO [linux_wlan_start_firmware]Firmware start timed out
WILC_SPI spi0.0 wlan0: ERR [wilc_wlan_initialize: 1196] Failed to start firmware
WILC_SPI spi0.0 wlan0: INFO [wlan_deinitialize_threads]Deinitializing Threads
WILC_SPI spi0.0 wlan0: INFO [wlan_deinitialize_threads]Deinit debug Thread
WILC_SPI spi0.0 wlan0: INFO [debug_thread]Exit debug thread
WILC_SPI spi0.0 wlan0: INFO [wlan_deinitialize_threads]Deinitializing Threads
WILC_SPI spi0.0 wlan0: INFO [linux_wlan_txq_task]txq_task Who waked me up
WILC_SPI spi0.0 wlan0: INFO [linux_wlan_txq_task]TX thread stopped
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_rxq_remove]Getting rxQ element
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_rxq_remove]Nothing to get from Q
WILC_SPI spi0.0 wlan0: INFO [wlan_deinit_locks]De-Initializing Locks
WILC_SPI spi0.0 wlan0: ERR [wilc_wlan_initialize: 1244] WLAN initialization FAILED
WILC_SPI spi0.0 wlan0: ERR [wilc_mac_open: 1294] Failed to initialize wilc
WILC_SPI spi0.0 wlan0: INFO [wilc_deinit]De-initializing host interface for client 1
WILC_SPI spi0.0 wlan0: INFO [wilc_send_config_pkt]Sending config SET PACKET WID:3079
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_cfg_set][WILC]PACKET Commit with sequence number0
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_txq_add_cfg_pkt]Adding config packet ...
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_txq_add_cfg_pkt]Return due to clear function
WILC_SPI spi0.0 wlan0: ERR [wilc_send_config_pkt: 1929] Set Timed out
WILC_SPI spi0.0 wlan0: ERR [handle_set_wfi_drv_handler: 445] Failed to set driver handler
WILC_SPI spi0.0 wlan0: Host cmd 24 failed
WILC_SPI spi0.0 wlan0: INFO [host_if_work]Releasing thread exit completion
WILC_SPI spi0.0 wlan0: ERR [host_if_work: 3000] [Host Interface] undefined
WILC_SPI spi0.0 wlan0: INFO [host_if_work]Releasing thread exit completion
WILC_SPI spi0.0 p2p0: INFO [wilc_mac_open]MAC OPEN[c794c800] p2p0
power up request for already powered up source Wifi
Device already up. request source is Wifi
WILC_SPI spi0.0 p2p0: INFO [wilc_init_host_int]Host[c794c800][c72be800]
WILC_SPI spi0.0 p2p0: INFO [wilc_init]Initializing host interface for client 1
WILC_SPI spi0.0 p2p0: INFO [wilc_init]INIT: CLIENT COUNT 0
WILC_SPI spi0.0 p2p0: INFO [wilc_mac_open]*** re-init ***
WILC_SPI spi0.0 p2p0: WRN [wilc_wlan_initialize: 1246]wilc already initialized
WILC_SPI spi0.0 p2p0: INFO [wilc_send_config_pkt]Sending config SET PACKET WID:3079
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_cfg_set][WILC]PACKET Commit with sequence number1
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_txq_add_cfg_pkt]Adding config packet ...
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_txq_add_cfg_pkt]Return due to clear function
WILC_SPI spi0.0 p2p0: ERR [wilc_send_config_pkt: 1929] Set Timed out
WILC_SPI spi0.0 p2p0: ERR [handle_set_wfi_drv_handler: 445] Failed to set driver handler
WILC_SPI spi0.0 p2p0: Host cmd 24 failed
WILC_SPI spi0.0 p2p0: INFO [host_if_work]Releasing thread exit completion
WILC_SPI spi0.0 p2p0: INFO [wilc_send_config_pkt]Sending config SET PACKET WID:2086
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_cfg_set][WILC]PACKET Commit with sequence number2
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_txq_add_cfg_pkt]Adding config packet ...
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_txq_add_cfg_pkt]Return due to clear function
WILC_SPI spi0.0 p2p0: ERR [wilc_send_config_pkt: 1929] Set Timed out
WILC_SPI spi0.0 p2p0: ERR [handle_set_operation_mode: 468] Failed to set driver handler
WILC_SPI spi0.0 p2p0: INFO [host_if_work]Releasing thread exit completion
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_txq_add_cfg_pkt]Adding config packet ...
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_txq_add_cfg_pkt]Return due to clear function
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_cfg_get]Get Response received
WILC_SPI spi0.0 p2p0: ERR [wilc_send_config_pkt: 1908] Get Timed out
WILC_SPI spi0.0 p2p0: ERR [handle_get_mac_address: 486] Failed to get mac address
WILC_SPI spi0.0 p2p0: INFO [host_if_work]Releasing thread exit completion
WILC_SPI spi0.0 p2p0: INFO [wilc_mac_open]Mac address: 00:00:00:00:00:00
WILC_SPI spi0.0 p2p0: ERR [wilc_mac_open: 1322] Wrong MAC address
WILC_SPI spi0.0 p2p0: INFO [wilc_deinit]De-initializing host interface for client 1
WILC_SPI spi0.0 p2p0: INFO [wilc_send_config_pkt]Sending config SET PACKET WID:3079
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_cfg_set][WILC]PACKET Commit with sequence number4
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_txq_add_cfg_pkt]Adding config packet ...
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_txq_add_cfg_pkt]Return due to clear function
WILC_SPI spi0.0 p2p0: ERR [wilc_send_config_pkt: 1929] Set Timed out
WILC_SPI spi0.0 p2p0: ERR [handle_set_wfi_drv_handler: 445] Failed to set driver handler
WILC_SPI spi0.0 p2p0: Host cmd 24 failed
WILC_SPI spi0.0 p2p0: INFO [host_if_work]Releasing thread exit completion
WILC_SPI spi0.0 p2p0: ERR [host_if_work: 3000] [Host Interface] undefined
WILC_SPI spi0.0 p2p0: INFO [host_if_work]Releasing thread exit completion
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_deinitialize]Deinitializing wilc  ...
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_deinitialize]Disabling IRQ
WILC_SPI spi0.0 wlan0: INFO [linux_wlan_disable_irq]Disabling IRQ ...
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_deinitialize]Deinitializing Threads
WILC_SPI spi0.0 p2p0: INFO [wlan_deinitialize_threads]Deinitializing Threads
WILC_SPI spi0.0 p2p0: INFO [wlan_deinitialize_threads]Deinit debug Thread
WILC_SPI spi0.0 p2p0: INFO [wlan_deinitialize_threads]Deinitializing Threads
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_deinitialize]Deinitializing IRQ
------------[ cut here ]------------
WARNING: CPU: 0 PID: 163 at kernel/irq/manage.c:1538 0xc0147e38
Trying to free already-free IRQ 121
Modules linked in: wilc_spi atmel_usba_udc
CPU: 0 PID: 163 Comm: dhcpcd Not tainted 4.14.73-linux4sam_6.0 #10
Hardware name: Atmel SAMA5
Function entered at [<c010d4a4>] from [<c010ab20>]
Function entered at [<c010ab20>] from [<c0116b30>]
Function entered at [<c0116b30>] from [<c0116b80>]
Function entered at [<c0116b80>] from [<c0147e38>]
Function entered at [<c0147e38>] from [<c01480a8>]
Function entered at [<c01480a8>] from [<bf00de60>]
Function entered at [<bf00de60>] from [<bf00ed14>]
Function entered at [<bf00ed14>] from [<bf00f1cc>]
Function entered at [<bf00f1cc>] from [<c051331c>]
Function entered at [<c051331c>] from [<c051365c>]
Function entered at [<c051365c>] from [<c051369c>]
Function entered at [<c051369c>] from [<c057bd28>]
Function entered at [<c057bd28>] from [<c04f4028>]
Function entered at [<c04f4028>] from [<c01d1114>]
Function entered at [<c01d1114>] from [<c01d190c>]
Function entered at [<c01d190c>] from [<c0107560>]
---[ end trace 303572b353c5f633 ]---
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_stop]Read RESET Reg fffffbfd : Retry10
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_stop]Bit 10 reset after : Retry 10
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_stop]Read RESET Reg fffffbfd : Retry10
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_deinitialize]Deinitializing WILC Wlan
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_rxq_remove]Getting rxQ element
WILC_SPI spi0.0 wlan0: INFO [wilc_wlan_rxq_remove]Nothing to get from Q
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_deinitialize]Deinitializing Locks
WILC_SPI spi0.0 p2p0: INFO [wlan_deinit_locks]De-Initializing Locks
WILC_SPI spi0.0 p2p0: INFO [wilc_wlan_deinitialize]wilc deinitialization Done

DTS file

			spi1: spi@fc000000 {
			        pinctrl-names = "default"; 
				pinctrl-0	= <&pinctrl_spi1_default>;
				cs-gpios = <&pioA PIN_PC5 GPIO_ACTIVE_LOW>;
				status = "okay";
				wilc_spi@0 {
					compatible = "microchip,wilc1000", "microchip,wilc3000", "atmel,wilc_spi";
					// compatible = "microchip,wilc3000","atmel,wilc_spi";
					spi-max-frequency = <12000000>;
					reg = <0>;
					gpio_reset =<&pioA PIN_PC10 GPIO_ACTIVE_HIGH>; 
					gpio_chip_en =<&pioA PIN_PC4 GPIO_ACTIVE_HIGH>; 
					gpio_irq = <&pioA PIN_PC9 GPIO_ACTIVE_LOW>;
					interrupt-parent = <&pioA>;
					status = "okay";
				};
			};
Regards,
Trilok

**Comment by AdhamAbozaeid** [comment]
Hi @TrilokJTReddy 

The log below
> WILC_SPI spi0.0 wlan0: INFO [linux_wlan_start_firmware]Firmware start timed out
points to a problem with the IRQ line or the interrupt handling.
At this point, the FW is successfully downloaded, and the dirver is waiting for an interrupt from the FW to indicate a successful start.
One way to make sure the FW started correctly, is to read the FW logs coming out from the WILC's uart lines with baudrate 115200. If you see meaningful logs, then the download was successful, and i would suspect a problem with the IRQ line, or with the interrupt handling.

Thanks,
Adham

**Comment by TrilokJTReddy** [comment]
Hi @AdhamAbozaeid 

Thank you, my problem is resolved. Problem is with hardware i.e., external 32Khz RTC clock is not going to device.

Regards,
Trilok

**Comment by AdhamAbozaeid** [comment]
Great! Thanks for confirming

**Comment by hildegardemalan** [comment]
Hi Trilok, 

May I ask which driver version you used for your build? I am struggling to get the ATWILC3000 working with the SAMA5D27 SOM1. From the debug it seems as though the ATWILC is entirely unresponsive.

Thanks, 
Hildegarde

**Comment by AdhamAbozaeid** [comment]
Hi @hildegardemalan 

The WILC Linux user guide here https://www.microchip.com/wwwproducts/en/ATWILC1000 has a section describing how to build for SAMA5D27.
Please follow this guide, and if you had problems using it, please open a ticket on salesforce

Thanks,
Adham

**Comment by hildegardemalan** [comment]
Hi Adham,

Thank you for contacting me. I have been trying to get the ATWILC3000 working with the SAMA5D27 SOM1 working for 2 months, using the guides you have referenced. I have an active support case with Microchip that I have now not heard anything from for a week.

If you have any advice you can offer, that would be much appreciated. I am at the point where I am considering moving on from the ATWILC3000 and using a different WiFi/BT module entirely.

I am uncertain what Salesforce is. I will open a ticket if you send a link to the website.

Kind regards,
Hildegarde

**Comment by AdhamAbozaeid** [comment]
Hi @hildegardemalan 
The salesforce link is http://microchipsupport.force.com/

**Comment by abhishekreddyR** [comment]
Hi @AdhamAbozaeid 

I am using WILC3000 interfaced using spi with my custom board sama5d27-som1-ek. I am facing issue with this my device is not getting powered up it is showing as shown below

**#modprobe wilc-spi
wilc_spi: module is from the staging directory, the quality is unknown, you have been warned.
WILC_SPI spi1.0: spiModalias: wilc1000, spiMax-Speed: 24000000
wifi_pm : 0
WILC_SPI spi1.0: failed to get Reset GPIO, try default
wifi_pm : 1
WILC_SPI spi1.0: failed to get Reset GPIO, try default
WILC_SPI spi1.0: WILC SPI probe success** 

The log
[wifi log.txt](https://github.com/linux4wilc/driver/files/5141779/wifi.log.txt)

My device tree binding for wilc spi is:


			**spi1: spi@fc000000 {
			        pinctrl-names = "default"; 
				pinctrl-0	= <&pinctrl_spi1_default>;
				cs-gpios = <&pioA PIN_PC5 GPIO_ACTIVE_LOW>;
				status = "okay";
				
				wilc_spi@0 {
					compatible = "microchip,wilc1000", "microchip,wilc3000", "atmel,wilc_spi";
				        spi-max-frequency = <24000000>;
					reg = <0>;
					gpio_reset =<&pioA PIN_PC10 GPIO_ACTIVE_HIGH>;
					gpio_chip_en =<&pioA PIN_PC4 GPIO_ACTIVE_HIGH>; 
					gpio_irq = <&pioA PIN_PC9 GPIO_ACTIVE_LOW>;
				 
					status = "okay";
				};
			};**	
Help me out where i am going wrong
