### ISSUE TITLE
wilc1000 soft AP configuration

### ISSUE THREAD

**Issue by ksathara** [linux4wilc/driver#45]
Hi, I have managed to compile the driver and integrate with Raspberry Pi CM3+. The station mode seems to be working fine. I just tried to implement AP mode as per "https://www.raspberrypi.org/documentation/configuration/wireless/access-point.md" and having some problems.
1. I dont see the AP 
2. After some time, I get the kernel oops
[  614.329355] Unable to handle kernel NULL pointer dereference at virtual address 00000000
[  614.342060] pgd = b7028145
[  614.347055] [00000000] *pgd=00000000
[  614.352903] Internal error: Oops: 5 [#1] SMP ARM
[  614.359735] Modules linked in: ipt_MASQUERADE iptable_nat nf_nat_ipv4 nf_nat nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 bcm2835_codec(C) snd_bcm2835(C) bcm2835_v4l2(C) v4l2_mem2mem v4l2_common bcm2835_mmal_vchiq(C) raspberrypi_hwmon videobuf2_vmalloc videobuf2_dma_contig snd_pcm videobuf2_memops hwmon snd_timer videobuf2_v4l2 videobuf2_common snd videodev media vc_sm_cma(C) fixed uio_pdrv_genirq uio wilc_sdio sha256_generic cfg80211 rfkill ip_tables x_tables ipv6
[  614.415740] CPU: 2 PID: 44 Comm: kworker/u8:1 Tainted: G         C        4.19.42-v7+ #2
[  614.426421] Hardware name: BCM2835
[  614.431167] Workqueue: WILC_wq handle_key [wilc_sdio]
[  614.437591] PC is at handle_key+0x218/0x80c [wilc_sdio]
[  614.444155] LR is at   (null)
[  614.448434] pc : [<7f18feec>]    lr : [<00000000>]    psr: 60000013
[  614.456057] sp : b9f9fe70  ip : b6064280  fp : b9f9ff0c
[  614.462643] r10: 00000000  r9 : 00000000  r8 : b6064240
[  614.469228] r7 : b9244320  r6 : 00000001  r5 : b9264500  r4 : b7026970
[  614.477090] r3 : 00000000  r2 : 00000000  r1 : 00000000  r0 : b6064250
[  614.484908] Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
[  614.493383] Control: 10c5383d  Table: 383e406a  DAC: 00000055
[  614.500496] Process kworker/u8:1 (pid: 44, stack limit = 0x28e486b5)
[  614.508243] Stack: (0xb9f9fe70 to 0xb9fa0000)

Any ides?

Cheers,
Kaushalyas

**Comment by ksathara** [comment]
Hi, From dmesg -w, I can see the point at which this kernel oops pops up.
[  616.574137] wilc_sdio mmc1:0001:1 wlan0: INFO [add_key]Adding key with cipher suite = fac04
[  616.574152] wilc_sdio mmc1:0001:1 wlan0: INFO [add_key]b83e41a0 b9eca000 2
[  616.574164] wilc_sdio mmc1:0001:1 wlan0: INFO [add_key]key d 68 c
[  616.574221] Unable to handle kernel NULL pointer dereference at virtual address 00000000
[  616.586832] pgd = 7f72c965
[  616.591729] [00000000] *pgd=00000000

There seems to be adding of some key happening just before the oops.

**Comment by AdhamAbozaeid** [comment]
Can you add more logs to handle_key() to see where exactly it fails?
you can also try the driver and FW from the dev branches since they have some updates

**Comment by AntoineBore** [comment]
I have a similar problem when I enable hostapd. If I start hostapd manually after the boot, so once the wilc1000 connection is complete, it works. But If hostapd is launched before the end of the wilc1000 initialization, the wifi module crash.

So I think you just need to start hostapd manually after the boot or find a solution so the hostapd service wait the end of the wilc1000 initialization. (I haven't found this solution yet but I will try to found it).

**Comment by AdhamAbozaeid** [comment]
@ksathara , any updates on that?
