### ISSUE TITLE
fix compilation for linux 4.14 kernel

### ISSUE THREAD

**Issue by tsifb** [linux4wilc/driver#65]
Current driver will not compile for 4.14.x kernel....

in wilc_wfi_init_mon_interface() this: 
#if KERNEL_VERSION(4, 15, 0) <= LINUX_VERSION_CODE
	wl->monitor_dev->needs_free_netdev = true;
#else
	wl->monitor_dev->destructor = free_netdev;
#endif

should be:
#if KERNEL_VERSION(4, 11, 9) <= LINUX_VERSION_CODE
	wl->monitor_dev->needs_free_netdev = true;
#else
	wl->monitor_dev->destructor = free_netdev;
#endif

similar issue in wilc_netdev_ifc_init()

**Comment by tsifb** [comment]
version 4.11.9 is where this structure changed, not 4.15.

**Comment by AdhamAbozaeid** [comment]
Thanks @tsifb .. that's correct
