### ISSUE TITLE
Kerner version check not fully fixed

### ISSUE THREAD

**Issue by dir-ableton** [linux4wilc/driver#72]
Hi,

while playing around with a the 15.3.1 version on our 4.14.X kernel we found two compilation errors. One is fixed in https://github.com/linux4wilc/driver/commit/cedf9ace28c54e5645abecd8df5a428f790e2a23 , but the other here https://github.com/linux4wilc/driver/blob/wilc_linux_15_3_1/wilc/wilc_mon.c#L299 is missing.

**Comment by AdhamAbozaeid** [comment]
Hi @dir-ableton 
The patch you pointed to fixes both errors in wilc_mon.c and wilc_netdev.c.
This will be released in 15.3RC2

**Comment by dir-ableton** [comment]
Oh, I'm sorry. Then there must have been something funky with our local cherry-pick/branching. Thanks!
