### ISSUE TITLE
"Debug Thread Running" messages creating too much noise on syslog

### ISSUE THREAD

**Issue by fsa-ableton** [linux4wilc/driver#74]
Hello,
I am seeing a lot of `*** Debug Thread Running ***` messages on my syslog. I'd like to know whether they can be safely ignored and if so, how to turn them off? They are creating a lot of noise in my system log.
Thanks a lot! :)

This refers to tag: `wilc_linux_15_3_1`

**Comment by AdhamAbozaeid** [comment]
Hi @fsa-ableton 
The log is safe to remove and its verbosity was already reduced to "debug" instead of "info" in commit a47ea8a97e33dcd8a1deaf09484ed3f2fcf7e227 on the dev branch.
If you are still seeing it, reduce your host's verbosity using "dmesg -n x" command.

Thanks,
Adham
