### ISSUE TITLE
Wifi AP won't connect dev branch

### ISSUE THREAD

**Issue by jackmitch** [linux4wilc/driver#75]
Hi,

On the latest dev branch with matching firmware + kernel v5.3 my wifi AP won't connect. This works OK on the master branch. It seems to hang for ~10 second at sending packet, do you have any idea what might be causing this?

dmesg: [bad_log.txt](https://github.com/linux4wilc/driver/files/3750270/bad_log.txt)

hostapd.conf

```
ssid=test
wpa_passphrase=test12345
interface=wlan1
channel=11
driver=nl80211
#logger_stdout=-1
#logger_stdout_level=2
rsn_pairwise=CCMP
wpa=3
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
ieee80211n=1
hw_mode=g
#ht_capab=[SHORT-GI-20][SHORT-GI-40][HT40+][HT40-][DSSS_CCK-40]
wmm_enabled=1
country_code=GB
ieee80211d=1
```
Test script:

```
root@via:~/wifi-ap# cat test-wifi.sh 
#! /usr/bin/env sh

function finish {
        echo "Cleaning up"
        killall udhcpd
        killall hostapd
}
trap finish INT

modprobe wilc-spi
iw dev wlan0 interface add wlan1 type __ap
/usr/sbin/hostapd -d hostapd.conf -P /run/hostapd.pid -B
ip addr flush dev wlan1
ip addr add 10.0.50.1/24 dev wlan1
udhcpd udhcpd.conf
read -r -d '' _
```

**Comment by jackmitch** [comment]
Sorry, this this was a configuration issue on my end.

**Comment by AdhamAbozaeid** [comment]
Thanks @jackmitch for the update

**Comment by jackmitch** [comment]
I did see some more issues with it after I closed this, I think it's something around the authentication side, my Android 10 phone seems to have issues with it, but my Linux desktop is OK. It's going to go through some more testing in the next couple of days and I'll update.
