### ISSUE TITLE
ATWILC3000-SHLD Schematic

### ISSUE THREAD

**Issue by vasubd** [linux4wilc/driver#80]
Can any one point to the ATWILC3000-SHLD schematic download link, 
https://www.microchip.com/DevelopmentTools/ProductDetails/PartNO/ATWILC3000-SHLD

we are trying to integrate the ATWILC300 using Shield board to PHYTEC phyBOARD-SEGIN
https://www.phytec.in/product/single-board-computer/phyboard-segin/

**Comment by AdhamAbozaeid** [comment]
The user guide is available here:
http://ww1.microchip.com/downloads/en/DeviceDoc/ATWILC3000-Shield-User-Guide-DS50002769A.pdf

I don't think the  phyBOARD-SEGIN has arduino headers. Are you planning to design a daughter board?
in this case, would using the WILC300 module http://ww1.microchip.com/downloads/en/DeviceDoc/70005327A.pdf a better option?
